name: Docker Image CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag itsmeteja9/sonarqube:${{ github.sha }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ITSMETJA9 }}
          password: ${{ secrets.ITSMETJA9 }}

      - name: Push Docker image to registry
        run: docker push itsmeteja9/sonarqube:${{ github.sha }}

      - name: Run Docker container from image
        run: |
          # Pull the image from the Docker registry (Docker Hub)
          docker pull itsmeteja9/sonarqube:${{ github.sha }}
          
          # Run the container in detached mode
          docker run -d --name sonarqube-container itsmeteja9/sonarqube:${{ github.sha }}
        
      - name: Verify the container is running
        run: docker ps
